steps:
  # Step 1: Use a Node.js image to install dependencies and build the application
  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        yarn
        yarn build

  # Step 2: Use the gcloud image to build a Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/it-books-store-431702', '.']

  # Step 3: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/it-books-store-431702']

  # Step 4: Deploy the application to Google Kubernetes Engine (GKE)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/deployment.yaml']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/service.yaml']
images:
  - 'gcr.io/$PROJECT_ID/it-books-store-431702'